n_features: 3
n_layers: 5
n_qubits: 10
learning_rate: 0.001
batch_size: 16
epochs: 800

# QNN Architecture
encoding_type: "angle"  # angle, amplitude, or basis
entanglement_type: "circular"  # linear, circular, full
measurement_type: "expval"  # expval, sample, or probs

# Training settings
optimizer: "Adam"
loss_function: "mse"
validation_split: 0.2
early_stopping: true
patience: 15

# Quantum device settings
device: "default.qubit"
shots: 2048
seed: 42

# Model checkpointing
save_checkpoints: true
checkpoint_frequency: 10
model_save_path: "qnn_model/model_checkpoints" 