# MoleQule Benchmarking Configuration
# Based on benchmark.md specifications

# Dataset Configuration
dataset:
  cisplatin_analogs:
    min_compounds: 30
    data_sources:
      - "PDBbind"
      - "BindingDB"
      - "ChEMBL"
      - "PubChem"
    quality_requirements:
      experimental_data: true
      crystal_structures: true
      validation_sources: 2
  
  targets:
    dna_targets:
      - name: "DNA_Duplex"
        pdb_ids: ["1AIO", "1AKE"]
        description: "Cisplatin-DNA complexes"
      - name: "Guanine_N7"
        description: "Primary binding site"
      - name: "Adenine_N3"
        description: "Secondary binding mechanism"
    
    protein_targets:
      - name: "GSTP1"
        pdb_id: "1GSE"
        description: "Glutathione S-transferase"
      - name: "KRAS_G12D"
        pdb_id: "4OBE"
        description: "Mutant KRAS"
      - name: "TP53"
        pdb_id: "1TUP"
        description: "Tumor suppressor"
      - name: "BRCA2"
        pdb_id: "1IYJ"
        description: "DNA repair protein"
    
    safety_targets:
      - name: "hERG"
        pdb_id: "5VA1"
        description: "Cardiac safety"
      - name: "Human_Albumin"
        pdb_id: "1AO6"
        description: "Protein binding"

# Docking Methods Configuration
docking_methods:
  molequle_methods:
    - name: "basic_analysis"
      description: "Simple geometric analysis"
      expected_performance: "baseline"
    
    - name: "qaoa_quantum"
      description: "Quantum-enhanced pose optimization"
      expected_performance: "superior"
    
    - name: "classical_force_field"
      description: "RDKit UFF force field docking"
      expected_performance: "industry_standard"
    
    - name: "grid_search"
      description: "Systematic conformational sampling"
      expected_performance: "comprehensive"
    
    - name: "autodock_vina"
      description: "AutoDock Vina integration"
      expected_performance: "gold_standard"
  
  baseline_methods:
    - name: "autodock_vina"
      description: "Industry standard (open source)"
    - name: "glide"
      description: "Schrödinger commercial software"
    - name: "gold"
      description: "Cambridge Crystallographic Data Centre"
    - name: "flexx"
      description: "BioSolveIT molecular docking"

# Performance Metrics
metrics:
  binding_affinity:
    - rmse: "Root Mean Square Error (kcal/mol)"
    - mae: "Mean Absolute Error (kcal/mol)"
    - r2: "Coefficient of determination"
    - spearman_rho: "Rank correlation coefficient"
  
  pose_quality:
    - rmsd: "Root Mean Square Deviation (Å)"
    - correct_pose_rate: "% of poses within 2Å RMSD"
    - binding_site_accuracy: "% correct binding pocket"
    - interaction_recovery: "% of key interactions found"
  
  statistical_validation:
    - paired_t_test: "Compare methods statistically"
    - confidence_intervals: "95% CI for performance metrics"
    - effect_size: "Cohen's d for practical significance"
    - cross_validation: "5-fold CV for robustness"

# Success Criteria
success_criteria:
  technical_performance:
    min_rmse: 2.0  # kcal/mol
    statistical_significance: 0.05
    reproducibility: 0.95  # confidence interval overlap
  
  experimental_validation:
    literature_correlation: 0.75  # R²
    pose_accuracy: 0.70  # 70%
    rank_order_accuracy: 0.80  # 80%
  
  commercial_readiness:
    performance_claims: true
    competitive_advantage: true
    market_validation: true

# Statistical Analysis
statistical:
  hypothesis_testing:
    null_hypothesis: "MoleQule performance = AutoDock Vina"
    alternative_hypothesis: "MoleQule performance > AutoDock Vina"
    significance_level: 0.05
    power_analysis: 0.80  # 80% power to detect 15% improvement
  
  multiple_testing:
    bonferroni_correction: true
    false_discovery_rate: true
    effect_size_reporting: true

# Implementation Settings
implementation:
  computing_environment:
    docker_container: true
    version_control: true
    dependency_management: true
  
  data_management:
    structured_datasets: true
    provenance_tracking: true
    backup_strategy: true
  
  results_storage:
    structured_output: "JSON"
    visualization_generation: true
    report_generation: true

# Timeline Configuration
timeline:
  phase_1_dataset: "Weeks 1-2"
  phase_2_platform: "Weeks 3-4"
  phase_3_benchmarking: "Weeks 5-6"
  phase_4_validation: "Weeks 7-8"
  phase_5_implementation: "Weeks 9-10"
  phase_6_commercial: "Weeks 11-12" 